import GlobalState from "@/context";
import NextThemeProvider from "@/theme-provider";
import "./globals.css";
import CommonLayout from "@/components/common-layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <NextThemeProvider>
            <CommonLayout>{children}</CommonLayout>
          </NextThemeProvider>
        </GlobalState>
      </body>
    </html>
  );
}
